Repository mbrn/material-table, pull requests merged in 2020-06, with the labels that each got.

#1787 change selection all to not select disabled rows (code404msg original author)
  demo/demo.js
  src/utils/data-manager.js
Labels: waiting for contributor

#1846 feat(typescript): update column.type definition
  types/index.d.ts
Labels: waiting for contributor

#2006 fixes #1969
  src/material-table.js
Labels: bug, has a solution, waiting for author

#1970 Add function for exporting table as PDF in addition to the CSV option.
  package.json
  src/components/m-table-toolbar.js
  src/material-table.js
Labels: waiting for contributor

#2004 Add prettier formating
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/help.md
  .github/actions/setup-node
  .github/pull_request_template.md
  .github/stale.yml
  .github/workflows/prettier.yml
  .travis.yml
  README.md
  configs/.babelrc
  configs/.eslintrc
  demo/demo.js
  demo/index.html
  demo/webpack.config.js
  package.json
  src/components/index.js
  src/components/m-table-action.js
  src/components/m-table-actions.js
  src/components/m-table-body-row.js
  src/components/m-table-body.js
  src/components/m-table-cell.js
  src/components/m-table-edit-field.js
  src/components/m-table-edit-row.js
  src/components/m-table-filter-row.js
  src/components/m-table-group-row.js
  src/components/m-table-groupbar.js
  src/components/m-table-header.js
  src/components/m-table-pagination.js
  src/components/m-table-stepped-pagination.js
  src/components/m-table-toolbar.js
  src/default-props.js
  src/index.js
  src/material-table.js
  src/prop-types.js
  src/utils/common-values.js
  src/utils/data-manager.js
  src/utils/index.js
  src/utils/polyfill/array.find.js
  src/utils/polyfill/index.js
  types/index.d.ts
Labels: enhancement, waiting for author
