Repository mbrn/material-table, pull requests merged in 2020-07, with the labels that each got.

#1998 Add error state
  src/components/m-table-body-row.js
  src/components/m-table-body.js
  src/components/m-table-cell.js
  src/components/m-table-edit-field.js
  src/components/m-table-edit-row.js
  src/components/m-table-filter-row.js
  src/components/m-table-toolbar.js
  src/default-props.js
  src/material-table.js
  src/prop-types.js
  types/index.d.ts
Labels: enhancement, feature, waiting for author

#2102 Allow exportFileName to be a function
  src/components/m-table-toolbar.js
  src/prop-types.js
  types/index.d.ts
Labels: waiting for author

#2045 Do not show hidden columns in columnsButton
  src/components/m-table-toolbar.js
  src/utils/data-manager.js
Labels: has-conflicts

#2008 Approve edit/add on enter added
  src/components/m-table-edit-row.js
Labels: has-conflicts

#2119 add groupTitle to options
  types/index.d.ts
Labels: waiting for contributor

#2120 add aria-label for the clear search button. fix up search aria-label …
  src/components/m-table-toolbar.js
Labels: has-conflicts

#2070 adds a new table option which allows a user to pass properties to the…
  demo/demo.js
  src/components/m-table-header.js
  src/default-props.js
  src/prop-types.js
  types/index.d.ts
Labels: has-conflicts

#2097 Changes ISO dates to use date-fns's parseISO function
  src/components/m-table-cell.js
Labels: bug, has-conflicts, waiting for author

#2114 guarding jsPDF to only import / run when window is present (aka not d…
  src/components/m-table-toolbar.js
Labels: has-conflicts, waiting for contributor
